### ISSUE TITLE
Auto Splitter can't be activated by LiveSplit 1.5.5

### ISSUE THREAD

**Issue by Dexter9313** [drtchops/LiveSplit.Skyrim#1] opened 2015-07-30 20:18 UTC
Whenever I try to activate it in LiveSlipt 1.5.5, LiveSplit tells me it cannot be activated.
To reproduce, it's easy : download a fresh install of LiveSplit, then activate The Elder Scrolls V : Skyrim auto splitter.
The Windows event logs tell this about this bug : 
"Cannot access a disposed object.
Object name: 'TimerForm'.

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at LiveSplit.View.TimerForm.TimerElapsed()"

Thanks a lot in advance for the fix, there is no way for me to run the game without an auto splitter.

**Comment by Dalet** [comment] 2015-07-30 20:32
I can't reproduce this. Do other autosplitters work? And did you upgrade to windows 10?
Edit: it seems antivirus false positives can cause this, try disabling it.

**Comment by Dexter9313** [comment] 2015-07-30 21:58
I am running on windows 7 and I tried disabling my antivirus which didn't help.
Other autosplitters work well, at least the Fallout 3 one does. It used to work when I had LiveSplit 1.4 so I don't think my antivirus would have done anything.
Actually what happened is that I updated from LiveSplit 1.4 so maybe some leftover files in who-knows-where are responsible for this but right now when I install LiveSplit 1.5.5 in a new folder, Skyrim auto splitter won't activate. Are there some new windows .net libs requirement or whatever ? I really don't know what is going on here. Could someone ship me a "bundled" version of LiveSplit+Skyrim autosplitter that is supposed to work please ? Maybe some file corruption occured in a very strange way.

**Comment by Dalet** [comment] 2015-07-30 22:15
Weird.
Is LiveSplit.Skyrim.dll present in your Components folder? Pressing Activate is supposed to download it.
You can download the dll manually here: https://github.com/drtchops/LiveSplit.Skyrim/raw/master/Components/LiveSplit.Skyrim.dll

Fallout 3's autosplitter is a script and not a component like Skyrim, try with the Dishonored one.

**Comment by Dexter9313** [comment] 2015-08-01 02:45
I know, right ? LiveSplit.Skyrim.dll is present in my Components folder and I already tried to download it manually (from another folder than the one you specified, but your file didn't work either). I tried the Dishonored one (and Dishonored (PC) ) and it activated like it's supposed to (although I don't have the game to check if it works, but at least it activated). Can I get your complete install of LiveSplit with Skyrim auto splitter working please so that we can check if it's my system or my LiveSplit install that is causing this problem ?

**Comment by Dalet** [comment] 2015-08-01 05:46
The installation only consists of having the .dll and having the autosplitter enabled in your split file.
This should load my splits with the autosplitter already enabled: http://puu.sh/jl2nd/afc9c62362.zip

Please keep your other installation and do this http://pastebin.com/M3n52ABV (since the error you posted isn't related).

**Comment by Dalet** [comment] 2015-08-20 19:42
Closing this until a new response from the author.

**Closed as completed by Dalet** 2015-08-20 19:42 UTC
